title: "Dr. Dot's Tutoring"
email: dot@macsix.io
description: >-
  Fun, friendly, expert science tutoring in Biology, Health and STEM with Dr. Dot.
baseurl: ""
url: "https://davidmacsix.github.io"

theme: jekyll-theme-so-simple
search_full_content: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
#header_pages:
#  - about.md
#  - faq.md
#  - contact.md
#  - blog.md

# Navigation for So Simple
navigation:
  - title: "About"
    url: /about/
  - title: "FAQ"
    url: /faq/
  - title: "Contact"
    url: /contact/
  - title: "Blog"
    url: /blog/

# Social Links
author:
  name: Dr. Dot
  email: dot@macsix.io

# Optional settings for So Simple
logo: "/assets/images/dot-profile.png"
locale: "en-GB"
markdown: kramdown
highlighter: rouge
