title: "Dr. Dot's International Tutoring"
subtitle: "Helping Curious Minds Thrive in Science"
email: dot@macsix.io
description: >-
  Fun, friendly, expert science tutoring in Biology, Health and STEM with Dr. Dot.
baseurl: ""
url: "https://macsix.io"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "air"

search_full_content: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

include: ["_pages", "_posts", "_data"]
exclude: ["README.md", "Gemfile", "Gemfile.lock", "LICENSE", "LICENSE.txt", ".idea"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
# Social Links
author:
  avatar: "/assets/images/dot-profile.png"
  name: Dr. Dorothy MacDonald
  bio: >-
    I am a passionate educator with a PhD in Immunology and over 17 years of experience in teaching and tutoring. I specialize in Biology, Health, and STEM subjects, making learning fun and engaging for students of all ages.
  links:
    - label: "dot@macsix.io"
      icon: "far fa-fw fa-envelope"
      url: "mailto:dot@macsix.io"
    - label: WhatsApp
      icon: "fab fa-fw fa-whatsapp"
      url: "https://wa.me/447973151425"
    - label: +44 7973 151425
      icon: "far fa-fw fa-phone"
      url: "tel:+447973151425"

logo: "/assets/images/logo.png"
locale: "en-GB"
markdown: kramdown
highlighter: rouge